# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sammyZi.Hyprism
PackageVersion: 1.2.5
InstallerType: inno
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sammyZi/Hyprism/releases/download/v1.2.5/Hyprism-Setup-1.2.5-x64.exe
  InstallerSha256: 55920C01BC8A3BC85B51A09B71C51E2B8C847A26AE3FC83A3F57FB3189A03E7D
  ProductCode: '{6E0D8A3B-5B7E-4E9C-9A55-3F1C2B7D9E41}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
